from __future__ import annotations

import builtins
import json
from pathlib import Path
from typing import Any

import pytest

from scripts.build_nemo_image_writer_parquet_fixtures import FIXTURES, build_fixtures
from vulca_curator_adapter.ingest.nemo_parquet import iter_nemo_parquet_signals

pa = pytest.importorskip("pyarrow")
pq = pytest.importorskip("pyarrow.parquet")


ROOT = Path(__file__).resolve().parents[1]
SOURCE_FIRST_COLUMNS = [
    "image_id",
    "tar_file",
    "member_name",
    "original_path",
    "metadata",
]
DOCUMENTED_ENRICHED_COLUMNS = SOURCE_FIRST_COLUMNS + [
    "aesthetic_score",
    "nsfw_score",
]


def _expected_schema(columns: list[str]) -> Any:
    return pa.schema(
        [
            pa.field(
                name,
                pa.float64()
                if name in {"aesthetic_score", "nsfw_score"}
                else pa.string(),
                nullable=False,
            )
            for name in columns
        ]
    )


def _source_rows(filename: str) -> list[dict[str, object]]:
    rows = json.loads((ROOT / "samples" / filename).read_text(encoding="utf-8"))
    assert isinstance(rows, list)
    return rows


def _signal_rows(path: Path) -> list[dict[str, Any]]:
    return [
        signal.model_dump(mode="json")
        for signal in iter_nemo_parquet_signals(path, batch_size=1)
    ]


def _copy_source_files(tmp_path: Path) -> Path:
    source_dir = tmp_path / "source"
    source_dir.mkdir()
    for source_name, _ in FIXTURES.values():
        (source_dir / source_name).write_text(
            (ROOT / "samples" / source_name).read_text(encoding="utf-8"),
            encoding="utf-8",
        )
    return source_dir


def _rewrite_source(
    source_dir: Path, fixture_name: str, rows: list[dict[str, object]]
) -> None:
    source_name = FIXTURES[fixture_name][0]
    (source_dir / source_name).write_text(
        json.dumps(rows, indent=2, allow_nan=True) + "\n",
        encoding="utf-8",
    )


def test_readable_sources_are_two_synthetic_rows_with_exact_column_order() -> None:
    source_first = _source_rows(FIXTURES["source_first"][0])
    documented_enriched = _source_rows(FIXTURES["documented_enriched"][0])

    assert len(source_first) == len(documented_enriched) == 2
    assert [list(row) for row in source_first] == [SOURCE_FIRST_COLUMNS] * 2
    assert [list(row) for row in documented_enriched] == [
        DOCUMENTED_ENRICHED_COLUMNS
    ] * 2
    assert [row["image_id"] for row in source_first] == [
        "source-first-001",
        "source-first-002",
    ]
    assert source_first[0]["metadata"] == (
        "{'source_url': 'https://example.com/nemo-source/source-first-001', "
        "'caption': 'Synthetic source-first candidate'}"
    )
    assert source_first[1]["metadata"] == "{}"
    serialized = json.dumps([source_first, documented_enriched])
    assert "".join(("/", "Users/")) not in serialized
    assert " ".join(("generated by", "NVIDIA")) not in serialized


def test_builds_exact_source_first_schema_rows_and_signals(tmp_path: Path) -> None:
    path = build_fixtures(ROOT / "samples", tmp_path)["source_first"]

    assert pq.ParquetFile(path).schema_arrow == _expected_schema(SOURCE_FIRST_COLUMNS)
    assert pq.read_table(path).to_pylist() == _source_rows(FIXTURES["source_first"][0])
    signals = list(iter_nemo_parquet_signals(path, batch_size=1))
    assert [signal.asset_id for signal in signals] == [
        "source-first-001",
        "source-first-002",
    ]
    assert [signal.aesthetic_score for signal in signals] == [None, None]
    assert [signal.nsfw_score for signal in signals] == [None, None]
    assert [signal.curator_metadata["parquet_provenance"] for signal in signals] == [
        {"sidecar": path.name, "row_number": 1},
        {"sidecar": path.name, "row_number": 2},
    ]


def test_builds_documented_enriched_compatibility_schema_and_signals(
    tmp_path: Path,
) -> None:
    path = build_fixtures(ROOT / "samples", tmp_path)["documented_enriched"]

    assert pq.ParquetFile(path).schema_arrow == _expected_schema(
        DOCUMENTED_ENRICHED_COLUMNS
    )
    assert pq.read_table(path).to_pylist() == _source_rows(
        FIXTURES["documented_enriched"][0]
    )
    signals = list(iter_nemo_parquet_signals(path, batch_size=1))
    assert [signal.asset_id for signal in signals] == [
        "documented-enriched-001",
        "documented-enriched-002",
    ]
    assert [signal.aesthetic_score for signal in signals] == [0.82, 0.18]
    assert [signal.nsfw_score for signal in signals] == [0.01, 0.02]
    assert [signal.curator_metadata["parquet_provenance"] for signal in signals] == [
        {"sidecar": path.name, "row_number": 1},
        {"sidecar": path.name, "row_number": 2},
    ]


def test_committed_parquet_files_semantically_match_regeneration(
    tmp_path: Path,
) -> None:
    regenerated = build_fixtures(ROOT / "samples", tmp_path)

    for name, (_, output_name) in FIXTURES.items():
        committed_path = ROOT / "samples" / output_name
        regenerated_path = regenerated[name]
        assert (
            pq.ParquetFile(committed_path).schema_arrow
            == pq.ParquetFile(regenerated_path).schema_arrow
        )
        assert (
            pq.read_table(committed_path).to_pylist()
            == pq.read_table(regenerated_path).to_pylist()
        )
        assert _signal_rows(committed_path) == _signal_rows(regenerated_path)


@pytest.mark.parametrize(
    "source_text",
    ["{}", "[]", "[{}]", "[{}, 1]", "[{}, {}, {}]"],
)
def test_malformed_source_shape_has_filename_scoped_error(
    tmp_path: Path, source_text: str
) -> None:
    source_dir = tmp_path / "source"
    source_dir.mkdir()
    source_name = FIXTURES["source_first"][0]
    (source_dir / source_name).write_text(source_text, encoding="utf-8")

    with pytest.raises(
        ValueError,
        match=rf"^{source_name}: expected a JSON array of exactly two objects$",
    ):
        build_fixtures(source_dir, tmp_path / "out")


def test_invalid_json_has_filename_scoped_error(tmp_path: Path) -> None:
    source_dir = tmp_path / "source"
    source_dir.mkdir()
    source_name = FIXTURES["source_first"][0]
    (source_dir / source_name).write_text("[", encoding="utf-8")

    with pytest.raises(ValueError, match=rf"^{source_name}: invalid JSON: "):
        build_fixtures(source_dir, tmp_path / "out")


@pytest.mark.parametrize("second_source_state", ["missing", "invalid"])
@pytest.mark.parametrize("existing_outputs", [False, True], ids=["absent", "sentinel"])
def test_second_source_failure_never_publishes_a_partial_fixture_set(
    tmp_path: Path,
    second_source_state: str,
    existing_outputs: bool,
) -> None:
    source_dir = _copy_source_files(tmp_path)
    second_source = source_dir / FIXTURES["documented_enriched"][0]
    if second_source_state == "missing":
        second_source.unlink()
    else:
        second_source.write_text("[", encoding="utf-8")

    out_dir = tmp_path / "out"
    sentinels = {
        output_name: f"old-{name}".encode()
        for name, (_, output_name) in FIXTURES.items()
    }
    if existing_outputs:
        out_dir.mkdir()
        for output_name, content in sentinels.items():
            (out_dir / output_name).write_bytes(content)

    with pytest.raises((FileNotFoundError, ValueError)):
        build_fixtures(source_dir, out_dir)

    if existing_outputs:
        assert {path.name for path in out_dir.iterdir()} == set(sentinels)
        assert {path.name: path.read_bytes() for path in out_dir.iterdir()} == sentinels
    else:
        assert not out_dir.exists()


def test_staging_write_failure_preserves_old_outputs_and_cleans_temporary_files(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    source_dir = _copy_source_files(tmp_path)
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    sentinels = {
        output_name: f"old-{name}".encode()
        for name, (_, output_name) in FIXTURES.items()
    }
    for output_name, content in sentinels.items():
        (out_dir / output_name).write_bytes(content)

    real_write_table = pq.write_table
    calls = 0

    def fail_second_write(*args: object, **kwargs: object) -> None:
        nonlocal calls
        calls += 1
        if calls == 2:
            raise OSError("synthetic second write failure")
        real_write_table(*args, **kwargs)

    monkeypatch.setattr(pq, "write_table", fail_second_write)

    with pytest.raises(OSError, match="synthetic second write failure"):
        build_fixtures(source_dir, out_dir)

    assert {path.name for path in out_dir.iterdir()} == set(sentinels)
    assert {path.name: path.read_bytes() for path in out_dir.iterdir()} == sentinels


def _install_second_publish_failure(
    monkeypatch: pytest.MonkeyPatch,
    out_dir: Path,
) -> OSError:
    real_replace = Path.replace
    second_output = FIXTURES["documented_enriched"][1]
    publication_error = OSError("synthetic second publish failure")
    failed = False

    def fail_second_publish_once(self: Path, target: Path) -> Path:
        nonlocal failed
        if (
            not failed
            and self.name == second_output
            and Path(target) == out_dir / second_output
        ):
            failed = True
            raise publication_error
        return real_replace(self, target)

    monkeypatch.setattr(Path, "replace", fail_second_publish_once)
    return publication_error


def _assert_restored_publication_error(
    caught: pytest.ExceptionInfo[Exception], publication_error: OSError
) -> None:
    assert isinstance(caught.value, RuntimeError)
    assert str(caught.value) == (
        "fixture publication failed; restored previous outputs: "
        "synthetic second publish failure"
    )
    assert caught.value.__cause__ is publication_error


def test_second_publish_failure_restores_both_existing_outputs(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    source_dir = _copy_source_files(tmp_path)
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    sentinels = {
        output_name: f"sentinel-{index}-{name}".encode()
        for index, (name, (_, output_name)) in enumerate(FIXTURES.items(), start=1)
    }
    for output_name, content in sentinels.items():
        (out_dir / output_name).write_bytes(content)
    publication_error = _install_second_publish_failure(monkeypatch, out_dir)

    with pytest.raises(Exception) as caught:
        build_fixtures(source_dir, out_dir)

    assert {path.name for path in out_dir.iterdir()} == set(sentinels)
    assert {path.name: path.read_bytes() for path in out_dir.iterdir()} == sentinels
    _assert_restored_publication_error(caught, publication_error)


def test_second_publish_failure_removes_new_output_when_both_started_absent(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    source_dir = _copy_source_files(tmp_path)
    out_dir = tmp_path / "out"
    publication_error = _install_second_publish_failure(monkeypatch, out_dir)

    with pytest.raises(Exception) as caught:
        build_fixtures(source_dir, out_dir)

    assert out_dir.exists()
    assert list(out_dir.iterdir()) == []
    _assert_restored_publication_error(caught, publication_error)


def test_rollback_failure_is_explicit_and_chained_from_publication_failure(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    source_dir = _copy_source_files(tmp_path)
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    for name, (_, output_name) in FIXTURES.items():
        (out_dir / output_name).write_bytes(f"sentinel-{name}".encode())

    real_replace = Path.replace
    second_output = FIXTURES["documented_enriched"][1]
    publication_error = OSError("synthetic second publish failure")
    rollback_error = OSError("synthetic rollback failure")
    publication_failed = False
    rollback_failed = False

    def fail_publication_then_rollback(self: Path, target: Path) -> Path:
        nonlocal publication_failed, rollback_failed
        if (
            not publication_failed
            and self.name == second_output
            and Path(target) == out_dir / second_output
        ):
            publication_failed = True
            raise publication_error
        if publication_failed and not rollback_failed:
            rollback_failed = True
            raise rollback_error
        return real_replace(self, target)

    monkeypatch.setattr(Path, "replace", fail_publication_then_rollback)

    with pytest.raises(
        RuntimeError,
        match=(
            "^fixture publication failed and rollback failed: "
            "publish error: synthetic second publish failure; "
            "rollback error: synthetic rollback failure$"
        ),
    ) as caught:
        build_fixtures(source_dir, out_dir)

    assert caught.value.__cause__ is publication_error
    assert {path.name for path in out_dir.iterdir()} == set(
        output_name for _, output_name in FIXTURES.values()
    )


def test_rejects_extra_column_in_second_row(tmp_path: Path) -> None:
    source_dir = _copy_source_files(tmp_path)
    source_name = FIXTURES["source_first"][0]
    rows = _source_rows(source_name)
    rows[1]["unexpected"] = "value"
    _rewrite_source(source_dir, "source_first", rows)

    with pytest.raises(
        ValueError,
        match=(
            rf"^{source_name}: row 2: expected columns in order: "
            rf"{', '.join(SOURCE_FIRST_COLUMNS)}; got: "
            rf"{', '.join(SOURCE_FIRST_COLUMNS)}, unexpected$"
        ),
    ):
        build_fixtures(source_dir, tmp_path / "out")


def test_rejects_missing_column_in_second_row(tmp_path: Path) -> None:
    source_dir = _copy_source_files(tmp_path)
    source_name = FIXTURES["source_first"][0]
    rows = _source_rows(source_name)
    rows[1].pop("metadata")
    _rewrite_source(source_dir, "source_first", rows)

    with pytest.raises(
        ValueError,
        match=(
            rf"^{source_name}: row 2: expected columns in order: "
            rf"{', '.join(SOURCE_FIRST_COLUMNS)}; got: "
            rf"{', '.join(SOURCE_FIRST_COLUMNS[:-1])}$"
        ),
    ):
        build_fixtures(source_dir, tmp_path / "out")


def test_rejects_reordered_columns_in_second_row(tmp_path: Path) -> None:
    source_dir = _copy_source_files(tmp_path)
    source_name = FIXTURES["source_first"][0]
    rows = _source_rows(source_name)
    rows[1] = {name: rows[1][name] for name in reversed(SOURCE_FIRST_COLUMNS)}
    _rewrite_source(source_dir, "source_first", rows)

    with pytest.raises(
        ValueError,
        match=(
            rf"^{source_name}: row 2: expected columns in order: "
            rf"{', '.join(SOURCE_FIRST_COLUMNS)}; got: "
            rf"{', '.join(reversed(SOURCE_FIRST_COLUMNS))}$"
        ),
    ):
        build_fixtures(source_dir, tmp_path / "out")


def test_rejects_wrong_string_type_with_row_context(tmp_path: Path) -> None:
    source_dir = _copy_source_files(tmp_path)
    source_name = FIXTURES["source_first"][0]
    rows = _source_rows(source_name)
    rows[1]["metadata"] = 42
    _rewrite_source(source_dir, "source_first", rows)

    with pytest.raises(
        ValueError,
        match=rf"^{source_name}: row 2: metadata must be a string$",
    ):
        build_fixtures(source_dir, tmp_path / "out")


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("aesthetic_score", True),
        ("aesthetic_score", float("nan")),
        ("aesthetic_score", -0.01),
        ("nsfw_score", 1.01),
        ("nsfw_score", "0.02"),
    ],
    ids=["bool", "non-finite", "below-zero", "above-one", "string"],
)
def test_rejects_invalid_enriched_score_with_row_context(
    tmp_path: Path, field: str, value: object
) -> None:
    source_dir = _copy_source_files(tmp_path)
    source_name = FIXTURES["documented_enriched"][0]
    rows = _source_rows(source_name)
    rows[1][field] = value
    _rewrite_source(source_dir, "documented_enriched", rows)

    with pytest.raises(
        ValueError,
        match=(
            rf"^{source_name}: row 2: {field} must be a finite real number "
            rf"between 0 and 1$"
        ),
    ):
        build_fixtures(source_dir, tmp_path / "out")


def test_missing_pyarrow_has_actionable_extra_guidance(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    real_import = builtins.__import__

    def blocked_pyarrow_import(
        name: str,
        globals: dict[str, object] | None = None,
        locals: dict[str, object] | None = None,
        fromlist: tuple[str, ...] = (),
        level: int = 0,
    ) -> Any:
        if name == "pyarrow" or name.startswith("pyarrow."):
            raise ModuleNotFoundError("blocked for test", name="pyarrow")
        return real_import(name, globals, locals, fromlist, level)

    monkeypatch.setattr(builtins, "__import__", blocked_pyarrow_import)

    with pytest.raises(
        ValueError,
        match=r'fixture generation requires pip install "\.\[nemo-parquet\]"',
    ):
        build_fixtures(ROOT / "samples", tmp_path)
